### ISSUE TITLE
_unexpected_death_handler don't stop all tasks just the task that failed

### ISSUE THREAD

**Issue by pelegn** [sybrenjansen/mpire#110]
Hello,

I'm using MPIRE, and im getting from time to time `RuntimeError(f"Worker-{worker_id} died unexpectedly")`
Still trying to investigate why this would happen.

From the code i see that after a worker dies "unexpectedly" all remaining tasks are set as failed.
I have 3 questions:
1. Any reason why not to let other tasks from other workers finish?
2. Is it possible to re-start the died worker?
3. If 2 is not possible, can we move the died worker jobs that haven't started yet to a different worker?

Thanks
Neta Peleg

**Comment by sybrenjansen** [comment]
Unexpected deaths usually means that the OS/kernel killed your process. One cause that jumps to mind is due to running out of memory. Maybe https://stackoverflow.com/questions/726690/what-killed-my-process-and-why can help you find the problem.

To answer your other questions:

If one task fails, you need to raise an exception at some time. I doesn't seem logical to not raise and let the others continue (as per your suggestion in 1), because how then would the user know something went wrong? And if we're raising, we might as well drop all the other tasks. 

Another option would be to built-in a retry mechanism. This would mean keeping track of all the tasks and its arguments and which worker got assigned which, and then redistributing the tasks over the other workers (or potentially restarting the dead worker). Although not impossible, this would make mpire a lot more complex and would require a lot of work to implement. Additionally, it would mean an increase in memory usage, although that could be mitigated by making it optional.

You can always make a feature request, but I'm not sure when I would be able to work on it as it will require quite some time.

**Comment by pelegn** [comment]
Thanks for the response, and thank you for the pointer to kernel killing link will definitely look into it. 

I think i missed putting some important information in my question.
I'm using `apply_async` for many tasks, and save the futures.
I then iterate over the futures and get the status back (which might be an exception).
In case of a "normal" exception there is no problem some tasks finish with success and some with an exception which i later on log or treat.
Not sure why this type of error should stop all tasks even if it was a memory issue which killed the process.

example for usage in a test

```
def task(run_time: float) -> int:
    time.sleep(run_time)
    return 1

def throw_exception() -> None:
    raise Exception("test")


def exit_with_code() -> None:
    sys.exit(1)


def test_worker_crashes() -> None:
    results = []
    with WorkerPool(start_method="spawn", n_jobs=1, daemon=False) as pool:
        results.append(pool.apply_async(task, args=(0.1,), task_timeout=0.5))
        results.append(pool.apply_async(throw_exception))
        results.append(pool.apply_async(exit_with_code))
        results.append(pool.apply_async(task, args=(0.1,), task_timeout=0.5))

    success = 0
    exception = 0
    sys_exit = 0
    num_results = len(results)
    while num_results:
        logger.info(f"Waiting for {num_results} results to finish")
        for result in results:
            try:
                if not result.ready():
                    continue
                num_results -= 1
                success += result.get()
            except Exception:
                exception += 1
            except SystemExit:
                sys_exit += 1
    assert success == 2
    assert exception == 1
    assert sys_exit == 1
```

Regarding the redistribution of work I understand that it would be a much more complex task.

**Comment by sybrenjansen** [comment]
You're right, for apply type tasks it doesn't make sense to kill all tasks. 

The only rationale I can give for why it is like it is, is that in the earlier stages of mpire there was no `apply` or `apply_async`, just the map functions. When the apply functions were added I simply didn't pay attention to the death handler that much, so it didn't get changed. My bad.

I will look into changing this in the near future for apply functions. It's still not as easy as it sounds though, because tasks can be put in the queue of the worker that just died. This means those tasks that haven't been worked on, and that weren't the cause of the death, get lost. So I will need to keep track of assigned tasks and redistribute them if one worker gets killed. Or put those all to failed, but that seems cumbersome.

**Comment by sybrenjansen** [comment]
This was actually easier to implement than I thought. I will create the PR tomorrow and release a new version somewhere this week.

What I implemented: when a worker dies because of the OS and it was working on an apply function, then it will be restarted and will continue with new tasks. The task that caused the death will be set to failed. 

The functionality hasn't changed when it dies and it was working on a map function, so still the entire pool will shut down. For now, that was the easiest way of going about it.
