### ISSUE TITLE
macOS support/testing

### ISSUE THREAD

**Issue by jonashaag** [sybrenjansen/mpire#91]
I'm interested in using mpire on macOS, however I'd like to run the tests first.

I naively added a macOS runner on GHA, but lots of the tests seem to fail:

https://github.com/jonashaag/mpire/actions/runs/6218986172/job/16876271887

**Comment by sybrenjansen** [comment]
Yes, that's because I've never tested it on mac :) Unfortunately, I don't own a macbook, so it's also something I cannot easily do. 

But if you're feeling adventurous, I'm happy to support you if you want to try to make mpire compatible with mac. 

It does seem to show the same error over and over again, so that's kinda encouraging. The function `drain_and_join_queue` in `comms.py` is mentioned, which creates a child process in which it tries to drain a queue. A queue in this case is a `JoinableQueue`, which uses the mentioned `SemLock` under the hood. If the queue is made in a `fork` context and the child process in a `spawn` context, I guess that gives this error. The default context on macOs is `spawn` I believe and if the unit test tests fork, that could be the issue. 

To remedy this you can replace `mp.Process` in `drain_and_join_queue` by a `self.ctx.Process`. That should fix that issue. However, I'm not sure which other errors might pop up after changing this.

**Comment by jonashaag** [comment]
Would you be interested in receiving a grant for a macOS VM where you can dev on, or are you not really interested in keeping things compatible with macOS long term?

**Comment by jonashaag** [comment]
It seems like this error and the one described here are the only problems https://github.com/sybrenjansen/mpire/issues/27

**Comment by jonashaag** [comment]
Another problem is the sheer amount of Queue, Lock, Value, Event, ... objects that outnumbers the default `ulimit -n` on macOS. Easily changed by setting `ulimit -n <max_expected_jobs * 8>` where 8 = number of objects

**Comment by jonashaag** [comment]
I wonder if we're missing out on some cleanup here https://github.com/sybrenjansen/mpire/blob/bdaa4c1e2269ecc2a157675818354cef39cae8f0/mpire/pool.py#L996-L1002

**Comment by sybrenjansen** [comment]
I might take you up on that. First, let me try to arrange a macbook at my current work. They're quite flexible, so if they have one lying around still, I might be able to get my hands on one

**Comment by sybrenjansen** [comment]
> I wonder if we're missing out on some cleanup here
> 
> https://github.com/sybrenjansen/mpire/blob/bdaa4c1e2269ecc2a157675818354cef39cae8f0/mpire/pool.py#L996-L1002

Hmm. That could very well be the case. I will have a look when I get the time

**Comment by sybrenjansen** [comment]
Unfortunately I'm not able to get my hands on a macbook. So, if that macOS VM is still an option I can give that a try. Can you point me to some resources on how to best go about this?

**Comment by sybrenjansen** [comment]
Update: I will be getting my hands on a macbook soon and because it will become my daily driver, I will probably have a look at full mpire support for mac in the very near future.

**Comment by sybrenjansen** [comment]
I did some initial testing. For that, I removed the `gc.collect` calls, such that all the leaked semaphores will show.

Interestingly, testing on different python versions I see that the `forkserver` start method is causing trouble in all python versions. From Python 3.10 onwards if you disable `forkserver`, there are no leaked semaphores and the tests consistently succeed. Going to Python 3.9 and below, we get leaked semaphores again, also for the other start methods.

So it seems like the python devs have fixed some issues from 3.10 onwards, but not for `forkserver` apparently. I will do some more debugging on how often semaphore cleanups are done, but I'm inclined to simply not support versions 3.9 and below for macos, and not support forkserver in general. You could still use it of course, but at your own risk.

**Comment by sybrenjansen** [comment]
I actually found the culprit of the leaked semaphores! Once fixed, all tests succeed on all Python versions, with all start methods, with zero leaked semaphores :)

In the mean time, I also tried to reduce the number of semaphores MPIRE needs in normal operation. Maybe a gc.collect will still help in some occassions, but that's something I still need to test.

Some stats with a simple test program with a very simple square function and a progress bar. I'm reporting how big I needed to set the ulimit in order to handle all the semaphores.

- Current master branch, 4 workers: ulimit to 160 and 10 leaked semaphores
- Current master branch, 10 workers: ulimit to 310 and 22 leaks
- New branch, 4 workers: ulimit to 110, 0 leaks
- New branch, 10 workers: ulimit to 190, 0 leaks

 So that's already a big win.
